version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vdemeester/tekton-lsp-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
